apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: 192.168.0.103:8000/producer
        ports:
        - containerPort: 5005
---
apiVersion: v1
kind: Service
metadata:
  name: producer-service
  labels:
    app: producer
spec:
  selector:
    app: producer
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5005
  type: ClusterIP