apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: 192.168.0.103:8000/consumer:0.0.1
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: consumer-service
  labels:
    app: consumer
spec:
  selector:
    app: consumer
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP